server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    # Serve SPA from index
    location / {
        try_files $uri $uri/ /index.html;
    }

    # /api/ strips itself from the request
    # path so the resulting url from
    # localhost:30000/api/<target>
    # is http://task-kube-service:4000/<target>
    location /api/ {
        proxy_pass http://task-kube-service:4000/;
    }
}

